# Generated by Django 3.0.7 on 2020-06-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curbalertapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
