# Generated by Django 3.0.7 on 2020-06-18 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curbalertapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerter',
            options={},
        ),
        migrations.AlterField(
            model_name='alerter',
            name='can_haul_away',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='alerter',
            name='haul_distance',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='alerter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='needs_haul_away',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='picked_up',
            field=models.BooleanField(null=True),
        ),
    ]
