# Generated by Django 3.0.7 on 2020-06-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curbalertapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='needs_haul_away',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='picked_up',
            field=models.BooleanField(default=False),
        ),
    ]
