# Generated by Django 3.0.7 on 2020-06-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curbalertapp', '0002_donation_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerter',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='alerter',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=18, null=True),
        ),
    ]
