# Generated by Django 3.0.7 on 2020-06-18 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curbalertapp', '0002_auto_20200618_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerter',
            name='haul_distance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curbalertapp.HaulDistance'),
        ),
        migrations.AlterField(
            model_name='alerter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerter', to=settings.AUTH_USER_MODEL),
        ),
    ]
