# Generated by Django 3.0.7 on 2020-06-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curbalertapp', '0003_auto_20200625_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='expires_on',
            field=models.DateTimeField(),
        ),
    ]
