# Generated by Django 3.0.7 on 2020-06-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curbalertapp', '0003_auto_20200627_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='expires_on',
            field=models.DateTimeField(default=None),
        ),
    ]
