# Generated by Django 3.0.7 on 2020-06-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curbalertapp', '0005_auto_20200628_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='expires_on',
            field=models.DateField(blank=True),
        ),
    ]
