# Generated by Django 3.0.7 on 2020-06-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curbalertapp', '0011_auto_20200628_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='expires_on',
            field=models.CharField(max_length=10),
        ),
    ]
