# Generated by Django 3.0.7 on 2020-06-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curbalertapp', '0014_auto_20200628_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerter',
            name='can_haul_away',
            field=models.BooleanField(default=True),
        ),
    ]
